name: Auto Rotate Tailscale AuthKey

on:
  schedule:
    # 每天凌晨 3 点自动执行
    - cron: "0 3 * */2 *"
  workflow_dispatch:

jobs:
  rotate_authkey:
    runs-on: ubuntu-latest

    env:
      GH_USER: ${{ secrets.GH_USER }}
      GH_PASS: ${{ secrets.GH_PASS }}
      GH_TOTP: ${{ secrets.GH_TOTP }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_REPO: ${{ github.repository }}
      SECRET_NAME: "TAILSCALE_AUTH_KEY"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pyotp requests pynacl
          playwright install chromium

      - name: Run Tailscale AuthKey rotation
        run: |
          python login.py
